import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.scss";

const vazirmatn = Vazirmatn({ subsets:["arabic"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirmatn.className}>{children}</body>
    </html>
  );
}
